name: particle-graph
channels:
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - umap-learn
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - prettytable
  - tqdm
  - PyYAML
  - tifffile
  - pydantic
  - gputil
  - pip
  - imageio
  - astropy
  - vispy
  - scikit-image
  - pysr
  - h5py
  - pip:
    - geomloss
    - torch_geometric
    - ipython
