description: 'system of particles falling down in a box  learning kernel + 4 steps Lr 5E-4 1E-5'
dataset: 'falling_water_ramp_wall'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/WaterRamps/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.05
  n_particles: 2800
  n_particle_types: 2
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_MLPs_C'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  multi_mlp_params: [[2, 128, 5, 5, 'relu'], [7, 32, 5, 4, 'relu'], [21, 128, 5, 16, 'relu'], [23, 128, 5, 16, 'relu'], [32, 64, 2, 2, 'none'], [4, 4, 2, 2, 'none']]   # input_size, hidden_size, nlayers, output_size

  aggr_type: 'add'
  embedding_dim: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]
  data_embedding: 3

training:
  n_epochs: 20
  batch_size: 20
  small_init_batch_size: False
  n_runs: 500

  noise_model_level: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: True
  translation_augmentation: False
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 5E-4
  learning_rate_embedding_start: 1E-5







