description: 'attraction-repulsion with 3 types particles and cell sequence state but no division n_particles_max: 600   1000 frames'
dataset: 'arbitrary_3_sequence_a'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055], [1.7226, 1.7850, 1.0584, 1.8579]]
  func_params: [['arbitrary', 0, 0], ['arbitrary', 1, 1], ['arbitrary', 2, 2]]

  min_radius: 0
  max_radius: 0.075
  n_particles: 4800
  n_particles_max: 600
  n_particle_types: 3
  n_frames: 1000
  sigma: 0.005
  delta_t: 0.1
  dpos_init: 0
  boundary: 'periodic'

  state_type: 'sequence'
  state_params: [ 250 ]

  cell_inert_model_coeff: 0.0
  cell_active_model_coeff: 1.0

graph_model:
  particle_model_name: 'PDE_A'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 5
  output_size: 2
  hidden_dim: 128
  n_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.04, 0.03]

training:
  n_epochs: 10
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'replace_embedding_function'
  sparsity_freq: 2
  cluster_method: 'kmeans_auto_plot'
  rotation_augmentation: True
  data_augmentation_loop: 200
  learning_rate_start: 0.001
  learning_rate_embedding_start: 0.001
  fix_cluster_embedding: True
  device: 'auto'
  sequence: ['none']

  coeff_model_a: 50





