description: 'attraction-repulsion with 3 types particles'
dataset: 'arbitrary_3_10'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055],  [0.03, 0.03, 100, 1.0]]
  func_params: [['arbitrary', 0, 0], ['arbitrary', 1, 1], ['tanh', 2, 2]]
  min_radius: 0
  max_radius: 0.075
  n_particles: 4800
  n_particle_types: 3
  n_frames: 1000
  sigma: 0.005
  delta_t: 0.05
  dpos_init: 0
  boundary: 'periodic'

graph_model:
  particle_model_name: 'PDE_A'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 5
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 10
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.04, 0.04]

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: False
  n_runs: 2
  sparsity: 'replace_embedding_function'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  coeff_continuous: 1.0E-1
  device: 'auto'





