# General
description:
  type: string

# Training
Nepochs:
  type: integer
  default: 20

noise_level:
  type: number
  default: 0

kmeans_input:
  type: string
  default: 'plot'

data_augmentation:
  type: boolean
  default: True

batch_size:
  type: integer
  default: 1
nrun:
  type: integer
  default: 2

clamp:
  type: number
  default: 0

pred_limit:
  type: number
  default: 1.E+10

sparsity:
  type: string
  default: 'none'

# Model parameters
model:
  type: string
  required: True

prediction:
  type: string
  required: True

input_size:
  type: integer
  required: True

output_size:
  type: integer
  required: True

hidden_size:
  type: integer
  required: True

n_mp_layers:
  type: integer
  required: True

aggr_type:
  type: string
  required: True

embedding:
  type: integer
  default: 2

upgrade_type:
  type: string
  default: 'none'
  
nlayers_update:
  type: integer
  default: 3
hidden_size_update:
    type: integer
    default: 64

# Simulation parameters
p:
  type: list
  required: True

radius:
  type: number
  required: True

c:
  type: list

min_radius:
  type: number
  default: 0

nparticles:
  type: integer
  default: 1000

nparticle_types:
  type: integer
  default: 5

ninteractions:
  type: integer
  default: 5

nframes:
  type: integer
  default: 1000

sigma:
  type: number

delta_t:
  type: number
  default: 1

v_init:
  type: number
  default: 0

boundary:
  type: string
  default: 'periodic'

particle_value_map:
  type: string

particle_type_map:
  type: string

beta:
  type: number

start_frame:
  type: integer
  default: 0

# Plotting
cmap:
  type: string
  default: 'tab10'

arrow_length:
  type: integer
  default: 10