description: 'Boids 16 different types'
dataset: 'boids_16_256_sparse'

simulation:
  params: [[27.6, 92.5, 0], [32.0, 0, 29.8], [0, 35.0, 13.5], [0, 0, 13.0], [94.0, 0, 0], [0, 34.6, 0], [3.1, 40.5, 17.0], [88.8, 0, 29.8], [0, 76.8, 26.1], [14.5, 56.8, 0], [0, 99.9, 13.9], [32.5, 0, 24.4], [97.6, 56.5, 0], [62.2, 9.1, 28.3], [76.4, 52.9, 32.0], [48.1, 54.4, 30.7]]
  min_radius: 0.001
  max_radius: 0.04
  n_particles: 1792
  n_particle_types: 16
  n_interactions: 16
  has_cell_division: False
  n_frames: 8000
  sigma: 0.005
  delta_t: 0.5
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_B'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  noise_level: 0
  rotation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'

