description: ''
dataset: 'fly_N8_1'

simulation:
    connectivity_file: 'to be specified'
    adjacency_matrix: ''

    params: [[1.0,1.0,1.0,1.0]]

    n_neurons: 2000
    n_neuron_types: 20
    n_frames: 2000
    delta_t: 0.01


graph_model:
    signal_model_name: 'PDE_N8'
    prediction: 'first_derivative'

    input_size: 5
    output_size: 1
    hidden_dim: 64
    n_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 20
    n_runs: 2
    device: 'auto'

    recursive_loop: 1
    batch_size: 1
    small_init_batch_size: False

    sparsity: 'none'
    rotation_augmentation: False
    data_augmentation_loop: 2000

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3

    noise_level: 0.5
    coeff_diff: 500
