description: 'test 10^5 time points  LRs 1E-4 5E-5 5E-4     synaptic network random matrix no recursive loop 1000 neurons 4 types lorentz std 0.03'
dataset: 'signal_N2_a60'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0],[10.0,2.0,1.0],[10.0,1.0,2.0],[10.0,2.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 1000
    n_particle_types: 4
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000

graph_model:
    signal_model_name: 'PDE_N2'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_mp_layers: 3

    input_size_update: 4
    n_layers_update: 5
    hidden_dim_update: 64

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'intricated'


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-8,8]

training:
    n_epochs: 20
    recursive_loop: 1
    batch_size: 1
    small_init_batch_size: True
    n_runs: 2
    device: 'auto'
    
    sparsity: 'none'
    rotation_augmentation: False
    epoch_reset: 1

    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    sparsity: 'replace_embedding_function'
    sparsity_freq: 4

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3

    noise_level: 1

