description: ''
dataset: 'signal_N4_e_1'

simulation:
    connectivity_file: 'values_-10.0_20.0'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'uniform'
    params: [[1.0,0.0,1.0,1.0,10.0],[1.0,0.0,0.1,1.0,10.0]]
    phi: 'sigmoid'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 2
    n_nodes: 2
    n_particle_types: 2
    shuffle_particle_types: False
    n_frames: 1000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: 0
    node_value_map: 'video_bisons_32.tif'

graph_model:
    field_type: 'excitation_single_500_10' #
    signal_model_name: 'PDE_N4'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 4
    output_size: 1
    hidden_dim: 64
    n_mp_layers: 5

    input_size_update: 4
    n_layers_update: 5
    hidden_dim_update: 128

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 32
    output_size_nnr: 1024
    omega: 30.0

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'intricated'
    
    lin_edge_positive: True


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [ -5,5 ]
    ylim: [ -8,8 ]

training:
    n_epochs: 20
    n_runs: 2
    device: 'auto'

    n_epochs_init: 5
    recursive_loop: 1
    batch_size: 1
    small_init_batch_size: True
    
    epoch_reset: 2
    epoch_reset_freq: 999
    n_epochs_init: 999

    rotation_augmentation: False
    data_augmentation_loop: 50
    
    sparsity: 'none'
    sparsity_freq: 4
    cluster_method: 'distance_plot'
    cluster_distance_threshold: 0.1
    fix_cluster_embedding: True

    coeff_diff: 100
    coeff_diff_update: 10 

    learning_rate_W_start: 1.0E-3
    learning_rate_start: 5.0E-4
    learning_rate_embedding_start: 5.0E-3
    learning_rate_modulation_start: 1.0E-4

    learning_rate_NNR: 1.0E-5
