description: 'synaptic network test learning with modulation     random matrix no recursive loop 1000 neurons 4 types lorentz std 0.03'
dataset: 'signal_N6_a29'

simulation:
    connectivity_file: ''
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0, 1.0, 1.0, 100, 0.02], [10.0, 2.0, 1.0, 100, 0.02], [10.0, 1.0, 2.0, 100, 0.02], [10.0, 2.0, 2.0, 100, 0.02]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 1024
    n_nodes: 1024
    n_particle_types: 4
    n_frames: 100000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: -2000

graph_model:
    field_type: 'Siren_short_term_plasticity_derivative'
    signal_model_name: 'PDE_N6'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    aggr_type: 'add'
    embedding_dim: 2

    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_mp_layers: 3

    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64

    input_size_modulation: 2
    n_layers_modulation: 3
    hidden_dim_modulation: 64
    output_size_modulation: 1

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 32
    output_size_nnr: 1024
    omega: 30

plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-8,8]

training:
    n_epochs: 60
    train_NNR_only: True

    recursive_loop: 1
    time_step: 1

    batch_size: 1
    small_init_batch_size: False

    n_runs: 2

    rotation_augmentation: False
    data_augmentation_loop: 25

    sparsity: 'none'
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    sparsity_freq: 4
    learning_rate_start: 1.0E-4

    coeff_diff: 100
    coeff_lin_modulation: 1.0E-3
    coeff_model_b: 1.0E-1

    learning_rate_W_start: 1.0E-4
    learning_rate_start: 5.0E-5
    learning_rate_embedding_start: 5.0E-4
    learning_rate_modulation_start: 1.0E-5

    learning_rate_NNR: 1.0E-6

    noise_level: 1

