description: 'attraction-repulsion with 3 types particles'
dataset: 'arbitrary_3_3'

simulation:
  params: [[ 0.0940,  0.8607,  2.2570,  1.8918],
         [ 0.7964,  1.1398,  1.4072,  0.3700],
         [ 2.8244,  2.8253,  0.3573,  0.2487],

        [ 0.2895, -0.2288,  2.5765,  0.7656],
         [ 1.0450, -0.2420, -1.3939,  1.4956],
         [ 0.9293,  0.3876,  1.5366, -0.3303],

        [-0.2636,  0.3685,  1.6940,  2.8136],
         [ 0.2971,  0.0469,  0.1975,  1.9027],
         [-0.0891,  0.8188,  2.2870,  1.1936]]
  min_radius: 0
  max_radius: 0.075
  n_particles: 4800
  n_particle_types: 3
  n_interactions: 9
  n_frames: 250
  sigma: 0.005
  delta_t: 0.1
  dpos_init: 0
  boundary: 'periodic'

graph_model:
  particle_model_name: 'PDE_A_bis'
  mesh_model_name: ''
  inter_model_name: ''
  prediction: 'first_derivative'
  input_size: 7
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: False
  n_runs: 2
  sparsity: 'replace_embedding'
  cluster_method: 'distance_plot'
  data_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'









