description: 'attraction-repulsion with 3 types particles and cell tracking no division 250 frames'
dataset: 'arbitrary_3_cell_tracking_a'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055], [1.7226, 1.7850, 1.0584, 1.8579]]
  cell_cycle_length: [ 129, 250, 248]
  cell_death_rate: [ 0,0,0 ]
  final_cell_mass: [ 100, 300, 400]
  min_radius: 0
  max_radius: 0.075
  n_particles: 4800
  n_particles_max: 600
  n_particle_types: 3
  n_frames: 250
  sigma: 0.005
  delta_t: 0.1
  dpos_init: 0
  boundary: 'periodic'
  has_cell_division: True
  has_cell_death: False
  has_cell_state: True
  state_params: [ 250 ]
  cell_inert_model_coeff: 0.0
  cell_active_model_coeff: 1.0

graph_model:
  particle_model_name: 'PDE_Cell_A'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 5
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.04, 0.03]

training:
  n_epochs: 10
  do_tracking: True
  batch_size: 1
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'replace_embedding_function'
  sparsity_freq: 2
  cluster_method: 'kmeans_auto_plot'
  rotation_augmentation: True
  data_augmentation_loop: 200
  learning_rate_start: 0.001
  learning_rate_embedding_start: 0.001
  fix_cluster_embedding: True
  device: 'auto'
  sequence: ['none']





