description: 'attraction-repulsion with 3 types particles'
dataset: 'arbitrary_3_division_death'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055], [1.7226, 1.7850, 1.0584, 1.8579]]
  cell_cycle_length: [-1]
  cell_death_rate: [1,2,3]
  min_radius: 0
  max_radius: 0.075
  n_particles: 2400
  n_particle_types: 3
  n_interactions: 3
  has_cell_division: True
  n_particles_max: 20000
  n_frames: 2000
  sigma: 0.005
  delta_t: 0.025
  dpos_init: 0
  boundary: 'periodic_special'

graph_model:
  particle_model_name: 'PDE_A'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 5
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  has_no_tracking: True
  batch_size: 1
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'replace_embedding_function'
  cluster_method: 'distance_plot'
  data_augmentation: True
  data_augmentation_loop: 50
  fix_cluster_embedding: True
  device: 'auto'





