description: 'Boids 16 different types, division'
dataset: 'arbitrary_division_model_passive_v'

simulation:
  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055],  [1.7226, 1.7850, 1.0584, 1.8579]]
  cell_cycle_length:  [560, 1012, 976]
  cell_death_rate: [0,0,0]
  final_cell_mass: [100, 300, 400]
  cell_area: [0.5,5,10]
  min_radius: 0.001
  max_radius: 0.04
  max_edges: 500000
  n_particles: 996
  has_cell_division: True
  has_cell_death: False
  cell_inert_model_coeff: 0.2
  coeff_area: 1
  coeff_perimeter: 2.5E-3
  cell_active_model_coeff: 0
  n_particles_max: 5000
  n_particle_types: 3
  n_frames: 400
  sigma: 0.005
  delta_t: 0.1
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0
  state_type: 'sequence'

graph_model:
  particle_model_name: 'PDE_Cell_A_area'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  sub_batches: 4
  n_runs: 2
  noise_level: 0
  sparsity: 'replace_embedding'
  cluster_method: 'distance_embedding'
  data_augmentation: True
  data_augmentation_loop: 200
  fix_cluster_embedding: True
  state_hot_encoding: True
  state_temperature: 1.0E-4
  device: 'auto'

