description: 'attraction-repulsion with 3 types particles'
dataset: 'arbitrary_3_3_bis'

simulation:
  params: [[ 1.5495,  0.5799, -0.7518, -0.4090],
         [ 0.1432,  2.6757,  1.5347,  1.5891],
         [ 0.7382,  0.2261,  1.7500,  0.5058],
        [ 0.5943,  2.1066,  2.5432,  2.2313],
         [ 0.9357,  0.8372,  1.2526,  1.3759],
         [ 0.8749,  0.5276,  1.3660,  0.6714],
        [-0.0041, -0.1353,  0.4642,  1.3960],
         [ 0.5669,  1.6539,  1.5360, -0.7057],
         [-0.2284, -0.1567,  1.4731,  2.0799]]
  min_radius: 0
  max_radius: 0.075
  n_particles: 4800
  n_particle_types: 3
  n_interactions: 9
  n_frames: 500
  sigma: 0.005
  delta_t: 0.05
  dpos_init: 0
  boundary: 'periodic'

graph_model:
  particle_model_name: 'PDE_A_bis'
  mesh_model_name: ''
  inter_model_name: ''
  prediction: 'first_derivative'
  input_size: 7
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  batch_size: 16
  small_init_batch_size: False
  n_runs: 2
  sparsity: 'replace_embedding'
  cluster_method: 'distance_plot'
  data_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'





