description: 'Boids 16 different types, division'
dataset: 'boids_16_division'

simulation:
  params: [[-1]]
  min_radius: 0.001
  max_radius: 0.04
  n_particles: 256
  has_cell_division: True
  n_particle_types: 16
  n_interactions: 16
  n_frames: 8000
  sigma: 0.005
  delta_t: 1
  dpos_init: 5.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_B_bis'
  mesh_model_name: ''
  inter_model_name: ''
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'
#  n_layers_update: 3
#  hidden_dim_update: 64

plotting:
  colormap: 'tab20'
  arrow_length: 5

training:
  n_epochs: 1
  batch_size: 1
  small_init_batch_size: True
  n_runs: 2
  noise_level: 0
  data_augmentation: True
  data_augmentation_loop: 1
  device: 'auto'

