description: 'Boids 16 different types, division'
dataset: 'boids_16_division_a'

simulation:
  params: [[ 7.4313, 93.6497, 81.4673],
        [21.4393, 38.4039, 11.4820],
        [17.1882, 65.0166, 89.1025],
        [75.1388, 56.7038, 59.3896],
        [44.2151,  9.5845,  1.0537],
        [77.2887,  8.1010, 91.2436],
        [58.2621, 51.9490, 80.1968],
        [34.3983, 73.6057, 23.9670],
        [31.8967, 65.2107, 15.6473],
        [73.2816, 14.1228, 79.7810],
        [13.9586, 90.6733, 86.0603],
        [96.7837, 93.8729,  1.0194],
        [91.1480, 40.3238,  1.8418],
        [28.9925, 79.4116, 38.5506],
        [28.6786, 96.7034, 15.7927],
        [39.1042, 98.0362, 31.9562]]
  min_radius: 0.001
  max_radius: 0.04
  n_particles: 1792
  has_cell_division: True
  n_particle_types: 16
  n_interactions: 16
  n_frames: 8000
  sigma: 0.005
  delta_t: 1
  dpos_init: 1.0E-4
  boundary: 'periodic'
  start_frame: 0

graph_model:
  name: 'PDE_B'
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 1
  noise_level: 0
  data_augmentation: True
  cluster_method: 'distance_plot'
  fix_cluster_embedding: True
  device: 'cuda:0'

