description: 'Gravity model with 16 different particle types'
dataset: 'brain'

simulation:
    connectivity_file: 'graphs_data/Brain.mat'
    params: [[1,1]]
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 998
    n_particle_types: 1
    n_interactions: 1
    n_frames: 1000
    delta_t: 1
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    particle_model_name: 'PDE_N'
    mesh_model_name: ''
    inter_model_name: ''
    prediction: 'first_derivative'
    input_size: 5
    output_size: 1
    hidden_dim: 128
    n_mp_layers: 5
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab20'
    arrow_length: 1

training:
    n_epochs: 20
    batch_size: 64
    small_init_batch_size: False
    n_runs: 2
    large_range: True
    learning_rate_start: 0.000001
    learning_rate_end: 0.0000005
    learning_rate_embedding_start: 0.0001
    learning_rate_embedding_end: 0.0001
    sparsity: 'none'
    data_augmentation: True
    data_augmentation_loop: 200
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
