description: 'Boids 16 different types, division'
dataset: 'cell_HeLa'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/HeLa/Fluo-N2DL-HeLa/01_ST/SEG/'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 100
  n_particles: 96
  has_cell_division: True
  has_cell_death: True
  n_particles_max: 8603
  n_particle_types: 16
  n_interactions: 16
  n_frames: 92
  delta_t: 1
  time_step: 10
  boundary: 'no'
  start_frame: 0

image_data:
    file_type: 'segmentation'

graph_model:
  particle_model_name: 'PDE_Cell'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 13
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  seed: 14
  n_epochs: 2
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1
  noise_level: 0
  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'auto'
  do_tracking: True
  learning_rate_start: 1.0E-4
  learning_rate_embedding_start: 1.0E-4

