data_folder_name: /groups/saalfeld/home/allierc/signaling/MDCK/Leica SGFP2 and H42
  nuclear marker/Larger center region/merged/
dataset: cell_MDCK
description: Boids 16 different types, division
graph_model:
  aggr_type: add
  embedding_dim: 2
  hidden_dim: 128
  input_size: 13
  mesh_model_name: ''
  n_mp_layers: 5
  output_size: 2
  particle_model_name: PDE_Cell
  prediction: first_derivative
  update_type: none
image_data:
  file_type: ''
plotting:
  arrow_length: 5
  colormap: tab20
  marker_size: 10
  ylim:
  - -0.0001
  - 0.0001
simulation:
  boundary: 'no'
  delta_t: 1
  has_cell_death: true
  has_cell_division: true
  max_radius: 250
  min_radius: 0
  n_frames: 92
  n_interactions: 16
  n_particle_types: 16
  n_particles: 96
  n_particles_max: 28167
  params:
  - - -1
  start_frame: 0
  time_step: 2
training:
  batch_size: 1
  cluster_method: distance_plot
  data_augmentation_loop: 5000
  device: auto
  do_tracking: true
  fix_cluster_embedding: true
  learning_rate_embedding_start: 0.0001
  learning_rate_start: 0.0001
  n_epochs: 2
  n_runs: 1
  noise_level: 0
  rotation_augmentation: true
  seed: 14
  small_init_batch_size: false
  sparsity: none
