Nepochs: 20
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0.002
nparticles: 960
nparticle_types: 16
ninteractions: 16
cluster_method: 'distance_plot'
nframes: 1000
sigma: 0.005
delta_t: 3.0E-5
v_init: 5.0E-5
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'GravityParticles'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: []
nrun: 2
clamp: 0
pred_limit: 1.0E+9
start_frame: -1000
arrow_length: 10
cmap: 'tab20'
arrow_length: 1
description: 'Gravity'
sparsity: 'regul_replace'
