input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.04
min_radius: 0
nparticles: 1800
nparticle_types: 4
ninteractions: 4
nframes: 2000
sigma: 0.005
tau: 1
v_init: 1E-3
aggr_type: 'mean'
boundary: 'periodic'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'PDE_B'
prediction: '2nd_derivative'
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
p: [[48.1, 54.4, 30.7], [21.4, 11.1,   43.8], [11.4, 28.5, 31.1], [34.2, 41.5,  34.7]]
nrun: 2
clamp: 0
pred_limit: 1E+9
start_frame: 0
cmap: 'tab10'
arrow_length: 5
description: 'Boids'
sparsity: 'regul_replace'
   
