Nepochs: 20
input_size: 8
output_size: 3
hidden_size: 32 
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0
nparticles: 10000 
nparticle_types: 4
nnodes: 10000
nnode_types: 4
ninteractions: 4
cluster_method: 'distance_plot'
nframes: 10000
sigma: 0.005 
delta_t: 0.1
v_init: 0
aggr_type: 'add'
boundary: 'periodic'
data_augmentation: True
batch_size: 1
embedding: 2
model: 'RD_RPS_Mesh'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: [0.2,1.4,2.6,3.8,5.0]
c: [0.4,0.8,1,0.6]
node_value_map: 'pattern_10.tif'
node_type_map: 'pattern_17.tif'
beta: 1
nrun: 2
clamp: 0
pred_limit: 1.0E+10
start_frame: 0
cmap: 'tab10'
arrow_length: 10
description: 'Wave equation 5 coefficients'
sparsity: 'none'

