Nepochs: 20
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.01
min_radius: 0.002
nparticles: 10000
nparticle_types: 5
ninteractions: 5
kmeans_input: 'plot'
nframes: 10000
sigma: 0.005
delta_t: 2
v_init: 5.0E-5
aggr_type: 'mean'
boundary: 'periodic'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'PDE_O'
prediction: '1st_derivative'
upgrade_type: 'none'
p: [0.2,0.4,0.6,0.8,1.0]
c: [0,0.6,0.8,1,0.7]
beta: 0
particle_value_map: 'pattern_10.tif'
particle_type_map: 'pattern_8.tif'
nrun: 2
clamp: 0
pred_limit: 1.0E+9
start_frame: 0
arrow_length: 10
cmap: 'tab20'
arrow_length: 1
description: 'Oscillator'
sparsity: 'replace'
