Nepochs: 20
input_size: 13
output_size: 3
hidden_size: 128
n_mp_layers: 8
noise_level: 0
radius: 0.075
min_radius: 0
input_dataset: '~/Desktop/signaling/4D_CElegans/log10_mean-and-smoothed_lin-32.csv'
dataset: 'CElegans_32'
nparticles: 4800
nparticle_types: 3
ninteractions: 3
nframes: 250
sigma: 0.005
tau: 0.1
v_init: 0
aggr_type: 'mean'
boundary: 'no' # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2 
model: 'PDE_A'
Nepochs: 100 
prediction: '1st_derivative'
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
p: [[1.0413, 1.5615, 1.6233, 1.6012], [1.8308, 1.9055, 1.7667, 1.0855], [1.785, 1.8579, 1.7226, 1.0584]]
nrun: 2
start_frame: 20
arrow_length: 20
cmap: 'tab10'
description: '3 interaction particles'
sparsity: 'none'
