Nepochs: 20
input_size: 11
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.15
min_radius: 0.001
nparticles: 960
nparticle_types: 3
ninteractions: 3
kmeans_input: 'plot'
nframes: 1000
sigma: 0.005
delta_t: 3.0E-5
v_init: 1.0E-4
aggr_type: 'add'
boundary: 'periodic' # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'PDE_E'
prediction: '2nd_derivative'
p: [[2], [1], [-1]]
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
nrun: 2
clamp: 0
pred_limit: 1.0E+10
start_frame: 0
arrow_length: 10
cmap: 'tab10'
description: 'Periodic PDE_E is a second derivative simulation, acceleration is function of electrostatic law qiqj/r2 interaction is type-type dependent'
sparsity: 'replace'
