Nepochs: 20
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0.001
nparticles: 960
nparticle_types: 16
ninteractions: 16
kmeans_input: 'embedding'
nframes: 2000
sigma: 0.005
delta_t: 2.5E-10
v_init: 2.5E-5
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'GravityParticles'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: []
nrun: 2
clamp: 0
pred_limit: 1E+9
start_frame: -500
arrow_length: 10
cmap: 'tab20'
arrow_length: 10
description: 'Gravity'
sparsity: 'regul_replace'
