ntry: 46
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.5
<<<<<<< HEAD
dataset: 231001_46
nparticles: 1024
=======
dataset: f'231001_46'
nparticles: 512
>>>>>>> fa78e7f8cf8d2fa3e21cb78f03f5ee0e3e11ec27
nparticle_types: 4
ninteractions: 4
nframes: 2000
sigma: .005
tau: 1E-9
v_init: 5E-4
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'GravityParticles'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: [0.2, 1.8, 3.4, 5.0]
nrun: 2
clamp: 0
pred_limit: 1E+20
start_frame: -1000
arrow_length: 10
cmap: 'tab10'
arrow_length: 10
description: 'Gravity'
sparsity: 'replace'
