dataset: 'arbitrary_3'
n_epochs: 20
input_size: 5
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.075
min_radius: 0
n_particles: 4800
n_particle_types: 3
n_interactions: 3
cluster_method: 'distance_plot'
n_frames: 250
sigma: 0.005
delta_t: 0.1
v_init: 0
aggr_type: 'mean'
boundary: 'periodic' # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 1
embedding: 2 
model: 'PDE_A'
prediction: 'first_derivative'
update_type: 'none'
n_layers_update: 3
hidden_size_update: 64
params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055], [1.7226, 1.7850, 1.0584, 1.8579]]
#[[1.0413, 1.5615, 1.6233, 1.6012], [1.8308, 1.9055, 1.7667, 1.0855], [1.785, 1.8579, 1.7226, 1.0584]]
n_runs: 2
clamp: 0
start_frame: 0
arrow_length: 2
colormap: 'tab10'
description: '3 interaction particles'
sparsity: 'regul_replace'
