Nepochs: 20
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0.002
nparticles: 960
nparticle_types: 8
ninteractions: 8
nframes: 1000
sigma: 0.005
tau: 1E-9
v_init: 5E-5
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'GravityParticles'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: [0.2, 1, 2, 3, 3.5, 4, 4.5, 5.0]
nrun: 2
clamp: 0
pred_limit: 1E+9
start_frame: -1000
arrow_length: 10
cmap: 'tab10'
arrow_length: 10
description: 'Gravity'
sparsity: 'regul_replace'
