input_size: 5
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.075
min_radius: 0
nparticles: 4800
nparticle_types: 5
ninteractions: 5
nframes: 250
sigma: 0.005
tau: 0.1
v_init: 0
aggr_type: 'mean'
boundary: 'periodic' # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2 
model: 'PDE_A'
prediction: 'first_derivative_S'
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
p: []
nrun: 2
clamp: 0
start_frame: 0
arrow_length: 20
cmap: 'tab10'
description: '3 interaction particles'
sparsity: 'regul_replace'
