ntry: 44
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.3
dataset: f'231001_44'
nparticles: 960
nparticle_types: 4
ninteractions: 4
nframes: 1000
sigma: .005
tau: 1E-9
v_init: 5E-5
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'GravityParticles'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: [0.2, 1.8, 3.4, 5.0]
nrun: 2
clamp: 0.002
pred_limit: 1E+9
start_frame: -1000
arrow_length: 10
cmap: 'tab10'
arrow_length: 10
description: 'Gravity'
sparsity: 'replace'
