input_size: 4
output_size: 2
hidden_size: 64
n_mp_layers: 5
noise_level: 0
radius: 0.075
min_radius: 0
dataset: 'arbitrary'
nparticles: 4800
nparticle_types: 3
ninteractions: 3
nframes: 200
sigma: 0.005
tau: 0.1
v_init: 0
aggr_type: 'mean'
boundary: 'periodic' # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 1
model: 'PDE_A'
prediction: 'first_derivative_S'
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
p: [[1.0413, 1.5615, 1.6233, 1.6012], [1.8308, 1.9055, 1.7667, 1.0855], [1.785, 1.8579, 1.7226, 1.0584]]
nrun: 2
start_frame: 20
arrow_length: 20
cmap: 'tab10'
description: '3 interaction particles'
sparsity: 'none'
