input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.04
min_radius: 0
nparticles: 1792
nparticle_types: 16
ninteractions: 16
nframes: 2000
sigma: 0.005
tau: 1
v_init: 1E-3
aggr_type: 'mean'
boundary: 'periodic'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'PDE_B'
prediction: '2nd_derivative'
upgrade_type: 'linear'
nlayers_update: 5
hidden_size_update: 64
p: [[27.6, 92.5, 48.2], [32.0, 51.8, 29.8], [23.6, 35.0, 13.5], [3.3, 76.4, 13.0], [94.0, 78.7, 30.8,], [81.4, 34.6, 2.2], [3.1, 40.5, 17.0], [88.8, 7.2, 29.8], [32.7, 76.8, 26.1], [14.5, 56.8, 27.6], [63.3, 99.9, 13.9], [32.5, 25.2, 24.4], [97.6, 56.5, 12.1], [62.2, 9.1, 28.3], [76.4, 52.9, 32.0], [48.1, 54.4, 30.7]]
nrun: 10
clamp: 0
pred_limit: 1E+9
start_frame: 0
cmap: 'tab20'
arrow_length: 5
description: 'Boids'
sparsity: 'none'
   
