Nepochs: 20
input_size: 9
output_size: 2
hidden_size: 128
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0.002
nparticles: 960
nparticle_types: 960
ninteractions: 960
cluster_method: 'distance_plot'
nframes: 2250
sigma: 0.005
delta_t: 1.5E-5
v_init: 2.5E-5
aggr_type: 'add'
boundary: 'no'  # periodic   'no'  # no boundary condition
data_augmentation: True
batch_size: 8
embedding: 2
model: 'PDE_G'
prediction: '2nd_derivative'
upgrade_type: 'none'
nlayers_update: 3
hidden_size_update: 64
p: [-1]
nrun: 2
clamp: 0
pred_limit: 1.0E+9
start_frame: -250
arrow_length: 10
cmap: 'tab20'
arrow_length: 1
description: 'Gravity'
sparsity: 'none'
