Nepochs: 20
input_size: 3
output_size: 1
hidden_size: 8 
n_mp_layers: 5
noise_level: 0
radius: 0.3
min_radius: 0
nparticles: 4225 
nparticle_types: 5
ninteractions: 5
nnodes: 10000
nnode_types: 5
cluster_method: 'distance_plot'
nframes: 2000
sigma: 0.005 
delta_t: 0.5
v_init: 0
aggr_type: 'add'
boundary: 'periodic'
data_augmentation: True
batch_size: 1
embedding: 2
model: 'WaveMesh'
prediction: '2nd_derivative'
upgrade_type: 'none'
p: [0.2,1.4,2.6,3.8,5.0]
c: [0,0.6,0.8,1,0.4]
particle_value_map: 'pattern_10.tif'
particle_type_map: 'pattern_8.tif'
beta: 1E-2 
nrun: 2
clamp: 0
pred_limit: 1E+10
start_frame: 0
cmap: 'tab10'
arrow_length: 10
description: 'Wave equation 5 coefficients'
sparsity: 'replace'

