description: 'system of particles falling down in a box'
dataset: 'falling_water_ramp'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/WaterRamps/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.015
  n_particles: 2800
  n_particle_types: 2
  n_interactions: 2
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_F'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  input_size: 20
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'add'
  embedding_dim: 2

  input_size_update: 12
  n_layers_update: 3
  hidden_dim_update: 128
  output_size_update: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 20
  batch_size: 1
  time_window: 4
  small_init_batch_size: True
  n_runs: 1000
  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  data_augmentation: False
  data_augmentation_loop: 2000
  fix_cluster_embedding: True
  learning_rate_start: 1.0E-3
  learning_rate_embedding_start: 1.0E-3
  device: 'auto'









