data_folder_name: /groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/WaterRamps/
dataset: falling_water_ramp_wall
description: system of particles falling down in a box
graph_model:
  aggr_type: add
  embedding_dim: 2
  hidden_dim: 128
  hidden_dim_update: 128
  input_size: 18
  input_size_update: 136
  mesh_model_name: ''
  n_layers_update: 4
  n_mp_layers: 4
  output_size: 128
  output_size_update: 2
  particle_model_name: PDE_WF
  prediction: 2nd_derivative
  update_type: mlp
image_data:
  file_type: ''
plotting:
  arrow_length: 2
  colormap: tab10
  ylim:
  - -0.001
  - 0
simulation:
  boundary: 'no'
  delta_t: 0.0025
  dpos_init: 1.0
  max_radius: 0.05
  min_radius: 0
  n_frames: 600
  n_interactions: 2
  n_particle_types: 2
  n_particles: 2800
  params:
  - - 0
    - 0.2
    - 0.4
    - 0.6
    - 0.8
  - - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2
  start_frame: 0
training:
  batch_size: 32
  cluster_method: kmeans_auto_embedding
  data_augmentation_loop: 5000
  device: auto
  fix_cluster_embedding: true
  learning_rate_embedding_start: 5E-5
  learning_rate_start: 5E-5
  n_epochs: 20
  n_runs: 500
  rotation_augmentation: false
  small_init_batch_size: false
  sparsity: none
  sparsity_freq: 3
  time_window: 4
  time_window_noise: 1.0e-05
  translation_augmentation: true
