description: 'system of particles falling down in a box'
dataset: 'falling_water_ramp'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/WaterRamps/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.15
  n_particles: 2400
  n_particle_types: 2
  n_interactions: 2
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_F'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  input_size: 22
  output_size: 128
  hidden_dim: 128
  n_mp_layers: 3
  aggr_type: 'add'
  embedding_dim: 2

  update_type: 'mlp'
  input_size_update: 140
  n_layers_update: 3
  hidden_dim_update: 128
  output_size_update: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 20
  batch_size: 32
  small_init_batch_size: False
  n_runs: 500
  time_window: 4
  time_window_noise: 0


  smooth_particle: True
  smooth_radius: 0.025
  smooth_function: 'triangular'

  recursive_loop: 0
  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: False
  translation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 5E-5
  learning_rate_embedding_start: 5E-5







