description: 'system of particles falling down in a box'
dataset: 'falling_particles_google'
data_folder_name: '/groups/saalfeld/home/allierc/Py/ParticleGraph/graphs_data/WaterDropSmall/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.01
  n_particles: 678
  n_particle_types: 2
  n_interactions: 2
  n_frames: 994
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_F'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 7
  output_size: 2
  hidden_dim: 64
  n_mp_layers: 3
  aggr_type: 'add'
  embedding_dim: 2

  input_size_update: 8
  n_layers_update: 3
  hidden_dim_update: 64
  output_size_update: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 20
  batch_size: 32
  small_init_batch_size: False
  n_runs: 20
  sparsity: 'replace_embedding'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  data_augmentation: False
  data_augmentation_loop: 500
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 5E-4
  learning_rate_embedding_start: 5E-4
  noise_level: 1.0E-5






