description: 'fluids simulation'
dataset: 'fluids_l1'

simulation:
  params: [[0, 1.0E-1, 3.86, 10.0]]
#  params: [[1.6233, 1.0413, 1.6012, 1.5615], [1.7667, 1.8308, 1.0855, 1.9055],  [1.7226, 1.7850, 1.0584, 1.8579]]
  min_radius: 0.001
  max_radius: 0.05
  n_particles: 4000
  n_particle_types: 3
  has_cell_division: False
  n_nodes: 10000
  n_frames: 2000
  sigma: 0.005
  delta_t: 0.0025
  dpos_init: 0 # 5.0E-1
  boundary: 'periodic'
  bounce: False
  start_frame: 0
  node_value_map: 'pattern_Null.tif'

graph_model:
  particle_model_name: 'PDE_B'
  mesh_model_name: ''

  field_grid: 'grid'
  field_type: 'calculus triangle'

  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5
  aggr_type: 'mean'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  ylim: [-1E-4, 1E-4]

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  noise_level: 0
  rotation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'

