description: 'Gravity model with 16 different particle types'
dataset: 'gravity_solar_system'
data_folder_name: 'graphs_data/solar_system'

simulation:
    dimension: 3
    params: [[-1]]
    min_radius: 1.0
    max_radius: 1.0E12
    n_particles: 25
    n_particle_types: 25
    n_interactions: 25
    n_frames: 70000
    delta_t: 14400 # 4*3600 seconds
    dpos_init:  5.0E-5
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    particle_model_name: 'PDE_GS'
    mesh_model_name: ''
    prediction: '2nd_derivative'
    input_size: 5
    output_size: 3
    hidden_dim: 256
    n_mp_layers: 5
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab20'
    arrow_length: 1

training:
    n_epochs: 20
    batch_size: 16
    small_init_batch_size: False
    n_runs: 2
    large_range: True
    sparsity: 'none'
    data_augmentation: False
    data_augmentation_loop: 1
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    learning_rate_start: 1.0E-4
    learning_rate_end: 1.0E-4
    learning_rate_embedding_start: 1.0E-4
    learning_rate_embedding_end: 1.0E-4
    device: 'auto'
