description: 'Gravity model with 16 different particle types'
dataset: 'gravity_100'

simulation:
    params: [-1]
    min_radius: 0.002
    max_radius: 0.3
    n_particles: 960
    n_particle_types: 16
    n_interactions: 16
    n_frames: 2250
    delta_t: 1.5E-5
    dpos_init:  2.5E-5
    boundary: 'no'
    start_frame: -250

graph_model:
    name: 'PDE_G'
    prediction: '2nd_derivative'
    input_size: 9
    output_size: 2
    hidden_dim: 128
    n_mp_layers: 5
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab20'
    arrow_length: 1

training:
    n_epochs: 20
    batch_size: 8
    small_init_batch_size: True
    n_runs: 2
    sparsity: 'replace'
    data_augmentation: True
    cluster_method: 'distance_plot'
    device: 'auto'
