description: 'maze mode, diffusion chemical  and boids'
dataset: 'particle_field_2'

simulation:
  params: [[27.6, 92.5, 48.2, 0.], [32.0, 51.8, 29.8, 0.], [23.6, 35.0, 13.5, 0.], [3.3, 76.4, 13.0, 0.], [94.0, 78.7, 30.8, 0.], [81.4, 34.6, 2.2, 0.], [3.1, 40.5, 17.0, 0.], [88.8, 7.2, 29.8, 0.], [32.7, 76.8, 26.1, 0.], [14.5, 56.8, 27.6, 0.], [63.3, 99.9, 13.9, 0.], [32.5, 25.2, 24.4, 0.], [97.6, 56.5, 12.1, 0.], [62.2, 9.1, 28.3, 0.], [76.4, 52.9, 32.0, 0.], [48.1, 54.4, 30.7, 0.]]
  min_radius: 0.001
  max_radius: 0.04
  n_particles: 1792
  n_particle_types: 16
  n_interactions: 16
  n_nodes: 10000
  n_node_types: 5
  diffusion_coefficients: [[0],[0.6],[0.8],[1],[0.4]]
  pos_rate: [[0.],[0.],[0.],[0.]]
  neg_rate: [[0.],[0.],[0.],[0.]]
  n_frames: 8000
  delta_t: 0.125
  dpos_init: 1.0E-4
  boundary: 'periodic'
  node_value_map: 'pattern_23.tif'
  node_type_map: 'pattern_8.tif'
  node_diffusion_map: 'pattern_8.tif'
  node_proliferation_map: 'pattern_15.tif'
  beta: 1.0E-2
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_ParticleField'
  mesh_model_name: 'Particle_Mesh'
  prediction: '2nd_derivative'
  input_size: 9
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'add'
  mesh_aggr_type: 'add'
  embedding_dim: 2
  input_size_update: 3
  n_layers_update: 3
  hidden_dim_update: 16
  output_size_update: 1

plotting:
  colormap: 'tab20'
  arrow_length: 10

training:
  n_epochs: 20
  noise_level: 0
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'replace_embedding'
  data_augmentation: True
  cluster_method: 'kmeans_auto_plot'
  fix_cluster_embedding: True



