description: 'FitzHugh_Nagumo model'
dataset: 'RD_FitzHugh_Nagumo'

simulation:
  params: [0,0,0,0]
  min_radius: 0
  max_radius: 0.3
  diffusion_coefficients: [0.4,0.8,1,0.6]
  n_particles: 10000
  n_particle_types: 4
  n_interactions: 4
  n_nodes: 10000
  n_node_types: 4
  n_frames: 10000
  delta_t: 0.1
  boundary: 'periodic'
  node_value_map: pattern_10.tif'
  node_type_map: 'pattern_17.tif'
  beta: 1

graph_model:
  name: 'RD_FitzHugh_Nagumo_Mesh'
  prediction: 'First_derivative'
  input_size: 8
  output_size: 3
  hidden_dim: 32
  n_mp_layers: 5
  aggr_type: 'add'
  mesh_aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 10

training:

  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 2
  sparsity: 'none'
  cluster_method: 'distance_plot'

  device: 'auto'
