description: 'Hemibrain + excitation video bisons excitation with siren recursive loop 2'
dataset: 'signal_N2_hemibrain_3_bison_1'

simulation:
    connectivity_file: '/groups/saalfeld/home/allierc/Py/ParticleGraph/graphs_data/graphs_signal_N2_hemibrain_3/adjacency_asym.pt'
    adjacency_matrix: ''
    excitation_value_map: 'video_bisons_60_1.tif'
    excitation: 'video'
    connectivity_init: [0,0.1]
    params: [[10.0,1.0],[10.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 2964
    n_particle_types: 2
    n_interactions: 2
    n_frames: 10000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    signal_model_name: 'PDE_N3'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_mp_layers: 3
    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'
    excitation_type: 'siren_with_time'

plotting:
    colormap: 'tab10'
    arrow_length: 1

training:
    n_epochs: 5
    recursive_loop: 2
    batch_size: 16
    small_init_batch_size: False
    n_runs: 10
    large_range: False
    sparsity: 'replace_embedding_function'
    sparsity_freq: 4
    data_augmentation: False
    data_augmentation_loop: 500
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    seed: 42
    coeff_L1: 1.0E-5
    n_no_siren: 0
    learning_rate_NNR: 1.0E-5



