description: 'Hemibrain'
dataset: 'signal_N2_hemibrain_4'

simulation:
    connectivity_file: 'conn-eb-fb-pb-no.tif'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    params: [[10.0,1.0],[10.0,2.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 2964
    n_particle_types: 2
    n_interactions: 2
    n_frames: 1000
    delta_t: 0.01
    dpos_init:  0
    boundary: 'no'
    start_frame: 0 # -1000

graph_model:
    signal_model_name: 'PDE_N3'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'
    input_size: 1
    output_size: 1
    hidden_dim: 64
    n_mp_layers: 3
    input_size_update: 3
    n_layers_update: 3
    hidden_dim_update: 64
    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'none'

plotting:
    colormap: 'tab10'
    arrow_length: 1

training:
    n_epochs: 10
    recursive_loop: 1
    batch_size: 16
    small_init_batch_size: False
    n_runs: 20
    large_range: False
    sparsity: 'none'
    data_augmentation: False
    data_augmentation_loop: 500
    cluster_method: 'distance_plot'
    fix_cluster_embedding: True
    device: 'auto'
    seed: 42
    coeff_L1: 1.0E-5
