description: 'test neuron_dependent functions  with CElegans data    idem a5   add  100 ghosts'
dataset: 'CElegans_a1'
data_folder_name: '/groups/saalfeld/home/allierc/Py/wormvae/data/worm_activity/all_traces_Heads_new.mat'
connectome_folder_name: '/groups/saalfeld/home/allierc/Py/wormvae/data/worm_connectivity/'

simulation:
    connectivity_file: 'random'
    adjacency_matrix: ''
    connectivity_init: [0,0.1]
    connectivity_distribution: 'Lorentz'
    params: [[10.0,1.0,1.0,1.0],[10.0,2.0,1.0,2.0],[10.0,1.0,2.0,4.0],[10.0,2.0,2.0,8.0]]
    phi: 'tanh'
    tau: 1.0
    min_radius: 1.0
    max_radius: 1.0E6
    n_particles: 189
    n_particle_types: 4
    n_frames: 800
    delta_t: 0.25
    dpos_init:  0
    boundary: 'no'
    start_frame: -1000

graph_model:
    signal_model_name: 'PDE_N4'
    particle_model_name: ''
    mesh_model_name: ''
    prediction: 'first_derivative'

    input_size: 3
    output_size: 1
    hidden_dim: 256
    n_mp_layers: 5

    input_size_update: 3
    hidden_dim_update: 64
    n_layers_update: 5

    input_size_excitation: 5
    n_layers_excitation: 3
    hidden_dim_excitation: 64

    input_size_nnr: 1
    n_layers_nnr: 5
    hidden_dim_nnr: 96
    output_size_nnr: 100
    omega: 30

    aggr_type: 'add'
    embedding_dim: 2
    update_type: 'excitation'
    excitation_dim: 3

    lin_edge_positive: True


plotting:
    colormap: 'tab10'
    arrow_length: 1
    xlim: [-5,5]
    ylim: [-8,8]

training:
    n_epochs: 20
    recursive_loop: 1
    batch_size: 8
    small_init_batch_size: False
    device: 'auto'
    n_runs: 21

    with_connectivity_mask: True

    n_ghosts: 100

    time_step: 8
    shared_embedding: True

    sparsity: 'none'
    rotation_augmentation: False
    data_augmentation_loop: 5000
    cluster_method: 'distance_embedding'
    cluster_distance_threshold: 0.2
    fix_cluster_embedding: True

    learning_rate_W_start: 1.0E-4
    learning_rate_start: 5.0E-5
    learning_rate_embedding_start: 5.0E-4

    learning_rate_NNR: 1.0E-6

    coeff_L1: 1.0E-6
    coeff_diff: 100
    coeff_L1_ghost: 1.0E-5
