description: 'attraction-repulsion with 3 types particles'
dataset: 'cell_gland_SMG2_smooth10'
data_folder_name: '/groups/wang/wanglab/GNN/240408-LVpD80-E10-IAI/SMG2-processed/masks_smooth10_label_props/'
data_folder_mesh_name: '/groups/wang/wanglab/GNN/240408-LVpD80-E10-IAI/SMG2-processed/masks_smooth10_mesh_csv/'

simulation:
  params: [[-1]]
  dimension: 3
  min_radius: 0
  max_radius: 20
  n_particles: 12774
  n_particles_max: 12774
  has_cell_division: True
  has_cell_death: True
  n_frames: 553
  delta_t: 1
  time_step: 2
  boundary: 'no'
  start_frame: 0

image_data:
    file_type: '3D masks meshes'

graph_model:
  particle_model_name: 'PDE_Cell_area'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 8
  output_size: 3
  hidden_dim: 128
  n_layers: 5
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1
  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: False
  data_augmentation_loop: 1000
  fix_cluster_embedding: True
  device: 'auto'
  do_tracking: True





