description: 'velocity field on cultured cardiomyocytes cells   test training 2nd_derivative + field + not remove self'
dataset: 'cell_cardio_2'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/cardiomyocytes/Cardio_1/0_B_15kPa_1_MMStack_Pos0.ome.tif.derivatives.npy'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 0.025
  n_particles: 18769
  n_particle_types: 1
  n_nodes: 18769
  n_frames: 239
  delta_t: 0.04166
  boundary: 'no'
  n_node_types: 1
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_MM_2layers'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  field_type: 'stimulus'

  aggr_type: 'add'
  embedding_dim: 2

  input_size: 10
  output_size: 64
  hidden_dim: 128
  n_layers: 5

  input_size_2: 134
  output_size_2: 128
  hidden_dim_2: 128
  n_layers_2: 5

  input_size_decoder: 128
  output_size_decoder: 2
  hidden_dim_decoder: 128
  n_layers_decoder: 3

  update_type: 'mlp'
  input_size_update: 5
  n_layers_update: 5
  hidden_dim_update: 128
  output_size_update: 2

  input_size_nnr: 3
  n_layers_nnr: 5
  hidden_dim_nnr: 64
  output_size_nnr: 1
  outermost_linear_nnr: True
  omega: 30.0


plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:

  n_runs: 2
  device: 'auto'
  n_epochs: 20

  batch_size: 4
  small_init_batch_size: False

  remove_self: False
  noise_level: 0

  sparsity: 'none'
  rotation_augmentation: False
  data_augmentation_loop: 500

  learning_rate_start: 1.0E-4
  learning_rate_embedding_start: 1.0E-4
  learning_rate_NNR: 1.0E-5

