description: 'Cells are MDCKs epithelial cells and surface is coated with fibronectin (FN)'
dataset: 'cell_MDCK_16'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/MDCK/jGcamp7b-mdcks-h42 11sec interval 5hrs/merged/'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 100
  n_particles: 96
  has_cell_division: True
  has_cell_death: True
  n_particles_max: 8603
  n_particle_types: 16
  n_frames: 4305
  delta_t: 1
  boundary: 'no'
  start_frame: 0

image_data:
    file_type: '2D fluo Cellpose'
    cellpose_channel: 0
    cellpose_diameter: 70
    cellpose_model: 'cyto2_cp3'
    cellpose_denoise_model: ''
    cellpose_channel: [2, 3]
    trackmate_size_ratio: 4.0
    trackmate_frame_step: 4
    offset_channel: [15, 0]
    measure_diameter: 0

graph_model:
  particle_model_name: 'PDE_Cell'
  mesh_model_name: ''
  prediction: 'first_derivative'
  input_size: 13
  output_size: 2
  hidden_dim: 128
  n_layers: 5
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  seed: 14
  n_epochs: 2
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1
  noise_level: 0
  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'auto'
  do_tracking: True
  learning_rate_start: 1.0E-4
  learning_rate_embedding_start: 1.0E-4

