description: 'cell_U2OS_3.yaml 128x128  2 passes'
dataset: 'cell_U2OS_10'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/U2OS/U2OS_003_small_128.tif'

simulation:
  params: [[0],[0],[0],[0]]
  min_radius: 0
  max_radius: 0.3
  diffusion_coefficients: [[0.02], [0.04], [0.05], [0.03]]
  n_particles: 16384
  n_particle_types: 4
  n_nodes: 16384
  n_node_types: 4
  n_frames: 181
  delta_t: 0.05
  boundary: 'periodic'

graph_model:
  field_grid: 'voronoi'
  particle_model_name: ''
  mesh_model_name: 'RD_RPS_Mesh2'
  prediction: 'first_derivative'

  input_size: 8
  output_size: 3
  hidden_dim: 256
  n_layers: 5

  input_size_update: 11
  output_size_update: 3
  hidden_dim_update: 256
  n_layers_update: 5

  aggr_type: 'add'
  mesh_aggr_type: 'add'

  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'viridis'
  arrow_length: 10

training:

  n_runs: 2
  device: 'cuda:0'

  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True

  data_augmentation_loop: 10000

  sparsity: 'none'
  cluster_method: 'distance_plot'
  fix_cluster_embedding: True


