description: 'velocity field on cultured cardiomyocytes cells'
dataset: 'cell_cardio_1'
data_folder_name: '~/Desktop/signaling/cardiomyocytes/healthy.npy'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 0.05
  n_particles: 6400
  n_particle_types: 16
  n_frames: 240
  delta_t: 0.04166
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_A'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 13
  output_size: 2
  hidden_dim: 128
  n_mp_layers: 5
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:

  n_runs: 2
  device: 'auto'
  n_epochs: 20

  batch_size: 1
  small_init_batch_size: False

  noise_level: 0

  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True

  learning_rate_start: 1.0E-4
  learning_rate_embedding_start: 1.0E-4

