description: 'Boids 16 different types, division'
dataset: 'cell_MDCK_4'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/MDCK/Leica SGFP2 and H42 nuclear marker/Position2-Center/merged/'

simulation:
  params: [[-1]]
  min_radius: 0
  max_radius: 0.2
  n_particles: 96
  has_cell_division: True
  has_cell_death: True
  n_particle_types: 16
  n_interactions: 16
  n_frames: 64
  delta_t: 1
  boundary: 'periodic'
  start_frame: 0

image_data:
    file_type: '2D fluo'
    cellpose_channel: 0
    cellpose_diameter: 75
    cellpose_model: '/groups/saalfeld/home/allierc/signaling/MDCK/Leica SGFP2 and H42 nuclear marker/training/models/CP_20250109_093212'
    cellpose_channel: [2, 1]

graph_model:
  particle_model_name: 'PDE_Cell'
  mesh_model_name: ''
  prediction: 'first_derivative'

  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'


  field_grid: 'grid'
  field_type: 'calculus gaussian density_gradient'

  prediction: '2nd_derivative'
  update_type: 'pre_mlp'
  aggr_type: 'add'

  pre_input_size: 2
  pre_output_size: 1
  pre_hidden_dim: 64
  pre_n_mp_layers: 3

  input_size: 1
  output_size: 1
  hidden_dim: 32
  n_mp_layers: 2
  embedding_dim: 2

  input_size_update: 1
  n_layers_update: 3
  hidden_dim_update: 128
  output_size_update: 2

plotting:
  colormap: 'tab20'
  arrow_length: 5
  marker_size: 10
  ylim: [-1.0E-4,1.0E-4]

training:
  seed: 14
  n_epochs: 2
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1
  noise_level: 0
  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'auto'
  do_tracking: True
  learning_rate_start: 1.0E-4
  learning_rate_embedding_start: 1.0E-4

