description: 'cell_U2OS_2.yaml 128x128  msg only'
dataset: 'cell_U2OS_8'
data_folder_name: '/groups/saalfeld/home/allierc/signaling/U2OS/U2OS_002_small_128.tif'

simulation:
  params: [[0],[0],[0],[0]]
  min_radius: 0
  max_radius: 0.01
  diffusion_coefficients: [[0.02], [0.04], [0.05], [0.03]]
  n_particles: 16384
  n_particle_types: 4
  n_nodes: 16384
  n_node_types: 4
  n_frames: 181
  delta_t: 0.05
  boundary: 'periodic'

graph_model:
  field_grid: 'voronoi'
  particle_model_name: ''
  mesh_model_name: 'RD_Mesh4'
  prediction: 'first_derivative'

  input_size: 5
  output_size: 3
  hidden_dim: 256
  n_layers: 5

  input_size_update: 8
  output_size_update: 3
  hidden_dim_update: 256
  n_layers_update: 5

  input_size_nnr: 2
  n_layers_nnr: 5
  hidden_dim_nnr: 128
  output_size_nnr: 1
  outermost_linear_nnr: True
  omega: 30.0

  aggr_type: 'add'
  mesh_aggr_type: 'add'

  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'viridis'
  arrow_length: 10

training:

  n_runs: 2
  device: 'cuda:0'

  n_epochs: 5
  batch_size: 8
  small_init_batch_size: True

  rotation_augmentation: False
  data_augmentation_loop: 2000

  sparsity: 'none'
  cluster_method: 'distance_plot'
  fix_cluster_embedding: True

  learning_rate_NNR: 1.0E-3


