description: 'system of particles falling down in a box   GNN encoder update decoder   test 10 loop update'
dataset: 'multimaterial'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/MultiMaterial/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.05
  n_particles: 2800
  n_particle_types: 5
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_MLPs_B_10'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  multi_mlp_params: [[18, 512, 4, 128], [256, 128, 2, 128], [128, 128, 3, 2], [4, 8, 2, 2]]   # input_size, hidden_size, nlayers, output_size

  aggr_type: 'add'
  embedding_dim: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]
  data_embedding: 17

training:
  n_epochs: 20
  batch_size: 20
  batch_ratio: 0.5
  small_init_batch_size: False
  n_runs: 999

  time_window: 4
  time_window_noise: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: True
  translation_augmentation: False
  data_augmentation_loop: 2000
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 1E-5
  learning_rate_embedding_start: 5E-5






