description: 'system of particles connected with spring possible coeffs 0 0.2 0.4 0.6 0.8'
dataset: 'springs_matrix_N5_3'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 1
  n_particles: 20
  n_particle_types: 3
  n_frames: 1000
  delta_t: 0.01
  dpos_init: 1.0E-5
  boundary: 'no'
  start_frame: -500

graph_model:
  particle_model_name: 'PDE_K'
  mesh_model_name: ''
  prediction: '2nd_derivative'
  input_size: 2
  output_size: 2
  hidden_dim: 64
  n_layers: 3
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'none'

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  n_runs: 2
  sparsity: 'none'
  cluster_method: 'distance_plot'
  rotation_augmentation: True
  data_augmentation_loop: 1000
  fix_cluster_embedding: True
  device: 'auto'





