description: 'fluids simulation'
dataset: 'fluids_m14'

simulation:
  params: [[-0.01, 1.0, 29.5, 25.0, 0.0], [-0.01, 1.0, 29, 25.0, 0.0], [-0.01, 1.0, 30, 25.0, 0.0], [-0.01, 1.0, 30.5, 25.0, 0.0]]
  min_radius: 0.001
  max_radius: 0.05
  n_particles: 6000
  n_particle_types: 4
  n_nodes: 10000
  n_frames: 40000
  sigma: 0.005
  delta_t: 0.005
  dpos_init: 0 # 5.0E-1
  pos_init: 'square'
  boundary: 'periodic'
  bounce: True
  bounce_coeff: 0.95
  start_frame: 0
  node_value_map: 'pattern_Null.tif'

graph_model:
  particle_model_name: 'PDE_F_A'
  mesh_model_name: ''

  field_grid: 'grid'
  field_type: 'calculus'

  prediction: '2nd_derivative'
  input_size: 11
  output_size: 2
  hidden_dim: 256
  n_layers: 5

  input_size_update: 2
  n_layers_update: 2
  hidden_dim_update: 8

  aggr_type: 'add'
  embedding_dim: 2

plotting:
  colormap: 'tab20'
  arrow_length: 5
  ylim: [-1E-4, 1E-4]
  speedlim: [0, 0.5]

training:
  n_epochs: 20
  n_runs: 2
  device: 'auto'

  batch_size: 8
  small_init_batch_size: False

  rotation_augmentation: False
  data_augmentation_loop: 10

  sparsity: 'none'
  fix_cluster_embedding: True

  learning_rate_start: 5E-6
  learning_rate_embedding_start: 1E-5

  noise_level: 0




