description: 'fluids simulation copy of m13_1 for boids simulation aggr=mean'
dataset: 'fluids_m20'

simulation:
  params: [[-0.01, 1.0, 39, 25.0, 0.0]]
  min_radius: 0.001
  max_radius: 0.05
  n_particles: 4000
  n_particle_types: 1
  has_cell_division: False
  n_nodes: 10000
  n_frames: 4000
  sigma: 0.005
  delta_t: 0.005
  dpos_init: 0 # 5.0E-1
  pos_init: 'square'
  boundary: 'periodic'
  bounce: True
  bounce_coeff: 0.6
  start_frame: 0
  node_value_map: 'pattern_Null.tif'

graph_model:
  particle_model_name: 'PDE_F'
  mesh_model_name: ''

  field_grid: 'grid'
  field_type: 'calculus triangle'

  prediction: '2nd_derivative'
  input_size: 9
  output_size: 124
  hidden_dim: 128
  n_layers: 4
  aggr_type: 'add'
  embedding_dim: 2
  update_type: 'mlp'

  input_size_update: 128
  n_layers_update: 4
  hidden_dim_update: 128
  output_size_update: 2

plotting:
  colormap: 'tab20'
  arrow_length: 5
  ylim: [-1E-4, 1E-4]
  speedlim: [0, 0.5]

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: True
  n_runs: 5
  noise_level: 0
  rotation_augmentation: False
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'

