description: 'fluids simulation'
dataset: 'fluids_m17_1_1'

simulation:
  params: [[0.0, 0.0, 0.0, 0.0, 0.0], [-0.01, 0.8, 27.0, 25.0, 1.0], [-0.01, 0.8, 28, 25.0, 1.0], [-0.01, 0.8, 29, 25.0, 1.0], [-0.01, 0.8, 30, 25.0, 1.0]]
  min_radius: 0.001
  max_radius: 0.05
  n_particles: 4900
  n_particle_types: 5
  n_nodes: 4900
  n_frames: 2000
  sigma: 0.005
  delta_t: 0.01
  dpos_init: 0 # 5.0E-1
  pos_init: 'square'
  boundary: 'periodic'
  bounce: True
  bounce_coeff: 0.95
  start_frame: 0
  node_value_map: 'pattern_Null.tif'

graph_model:
  particle_model_name: 'PDE_MLPs_A'
#  particle_model_name: 'PDE_F_A'

  mesh_model_name: ''
  prediction: '2nd_derivative'

  field_grid: 'grid'
  field_type: 'calculus'

  multi_mlp_params: [[2, 128, 5, 5], [7, 32, 5, 4], [23, 256, 10, 2], [4, 8, 2, 2]]   # input_size, hidden_size, nlayers, output_size

  kernel_type: 'siren'

  omega: 30.0

  aggr_type: 'add'
  embedding_dim: 2

plotting:
  colormap: 'tab20'
  arrow_length: 5
  ylim: [-1E-4, 1E-4]
  speedlim: [0, 0.5]
  data_embedding: 1

training:
  n_epochs: 20
  batch_size: 4
  small_init_batch_size: False
  n_runs: 2

  time_window_noise: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: True
  translation_augmentation: False
  data_augmentation_loop: 200
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 5E-5
  learning_rate_embedding_start: 1E-4




