description: 'training next C F Jp  LR:1E-5 LR_embedding:1E-2 next_S smaller MLP_F'
dataset: 'multimaterial_1'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.0125
  n_particles: 9000
  n_grid: 128
  n_particle_types: 3
  n_frames: 1000
  delta_t: 1.E-4
  dpos_init: 1.0
  boundary: 'no'
  start_frame: -1000

graph_model:
  particle_model_name: 'PDE_MPM'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  input_size: 18
  output_size: 512
  hidden_dim: 512
  n_layers: 4
  aggr_type: 'add'
  embedding_dim: 2

  update_type: 'mlp'
  input_size_update: 520
  n_layers_update: 4
  hidden_dim_update: 128
  output_size_update: 2

  input_size_nnr: 3
  n_layers_nnr: 5
  hidden_dim_nnr: 512
  output_size_nnr: 4
  outermost_linear_nnr: True
  omega: 30.0

  # Siren parametrization: [in_features, out_features, hidden_features, hidden_layers, first_omega_0, hidden_omega_0, outermost_linear]
  # Order: [F, Jp, C_normal, C_PDE_MPM_A]
  multi_siren_params:
    - [ 3, 4, 512, 5, 30.0, 30.0, true ]    # siren_F
    - [ 3, 1, 512, 5, 30.0, 30.0, true ]    # siren_Jp
    - [ 5, 4, 512, 5, 30.0, 30.0, true ]    # siren_C normal
    - [ 7, 4, 512, 5, 30.0, 30.0, true ]    # siren_C PDE_MPM_A

  # MLP parametrization: [input_size, output_size, n_layers, hidden_size, initialisation]
  # Order: [mu_lambda, sig, F, stress]
  multi_mlp_params:
    - [3, 2, 3, 32, "normal"]      # MLP_mu_lambda
    - [4, 2, 5, 32, "ones"]        # MLP_sig
    - [15, 4, 5, 64, "normal"]    # MLP_F
    - [11, 4, 5, 128, "normal"]    # MLP_stress

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 3
  batch_size: 1
  small_init_batch_size: False
  n_runs: 1

  noise_model_level: 0
  noise_model_level: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: False
  translation_augmentation: True
  data_augmentation_loop: 100
  fix_cluster_embedding: True
  device: 'auto'

  learning_rate_start: 1E-5
  learning_rate_embedding_start: 1E-2

  MPM_trainer : 'next_S'

  coeff_Jp_norm: 1E-3
  coeff_F_norm: 1E-3