description: 'system of particles falling down in a box  redo 8_1 with PDE_MLPs'
dataset: 'multimaterial'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/MultiMaterial/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.05
  n_particles: 2800
  n_particle_types: 5
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

graph_model:
  particle_model_name: 'PDE_MLPs_C'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  multi_mlp_params: [[11, 256, 5, 2]]   # input_size, hidden_size, nlayers, output_size

  input_size: 11
  output_size: 2
  hidden_dim: 256
  n_mp_layers: 5

  aggr_type: 'add'
  embedding_dim: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]
  data_embedding: 17

training:
  n_epochs: 20
  batch_size: 8
  small_init_batch_size: False
  n_runs: 999

  time_window_noise: 1.0E-5

  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: False
  translation_augmentation: False
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'cuda:1'

  learning_rate_start: 5.0E-5
  learning_rate_embedding_start: 5.0E-4







