description: 'system of particles falling down in a box'
dataset: 'falling_water_ramp_wall'
data_folder_name: '/groups/saalfeld/saalfeldlab/projects/gnn/learning-to-simulate/WaterRamps/'

simulation:
  params: [[0, 0.2, 0.4, 0.6, 0.8], [0.2, 0.2, 0.2, 0.2, 0.2]]
  min_radius: 0
  max_radius: 0.05
  n_particles: 10000
  n_particle_types: 2
  n_interactions: 2
  n_frames: 600
  delta_t: 0.0025
  dpos_init: 1.0
  boundary: 'no'
  start_frame: 0

  smooth_radius: 0.05

graph_model:
  particle_model_name: 'PDE_WF'
  mesh_model_name: ''
  prediction: '2nd_derivative'

  pre_input_size: 1
  pre_output_size: 1
  pre_hidden_dim: 128
  pre_n_mp_layers: 4

  input_size: 7
  output_size: 1
  hidden_dim: 128
  n_mp_layers: 4
  aggr_type: 'add'
  embedding_dim: 2

  update_type: 'pre_mlp'
  input_size_update: 5
  n_layers_update: 3
  hidden_dim_update: 128
  output_size_update: 2

plotting:
  colormap: 'tab10'
  arrow_length: 2
  ylim: [-0.001, 0]

training:
  n_epochs: 20
  batch_size: 1
  small_init_batch_size: False
  n_runs: 2
  time_window: 0
  time_window_noise: 0

  recursive_loop: 0
  sparsity: 'none'
  sparsity_freq: 3
  cluster_method: 'kmeans_auto_embedding'
  rotation_augmentation: False
  translation_augmentation: True
  data_augmentation_loop: 5000
  fix_cluster_embedding: True
  device: 'cpu'

  learning_rate_start: 1E-5
  learning_rate_embedding_start: 1E-5







